version: '3'
services:
  database:
    container_name: postgres
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-test}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - ./:/go/src/github.com/Scalingo/sclng-backend-test-v1
    ports:
      - "5000:5000"
    command: reflex -r '\.go$$' -s -- sh -c 'go build -buildvcs=false && ./sclng-backend-test-v1'
    stop_signal: SIGKILL
    depends_on:
      - database
volumes:
  pg_data: {}